set(TOOL_SOURCE "${TEST_ROOT}/source")
set(TOOL_DESTINATION "${TEST_ROOT}/destination")
file(MAKE_DIRECTORY "${TOOL_SOURCE}/example/state" "${TOOL_DESTINATION}/example/state")
file(WRITE "${TOOL_SOURCE}/example/tool.txt" "version-1")
file(WRITE "${TOOL_SOURCE}/example/state/current.json" "must-not-ship")
file(WRITE "${TOOL_DESTINATION}/example/state/current.json" "user-state")
include("${SYNC_SCRIPT}")
file(READ "${TOOL_DESTINATION}/example/state/current.json" state)
if(NOT state STREQUAL "user-state")
    message(FATAL_ERROR "Runtime state was overwritten")
endif()
# Give the new script a different size; file(COPY) can use size and mtime.
file(WRITE "${TOOL_SOURCE}/example/tool.txt" "version-2-updated")
include("${SYNC_SCRIPT}")
file(READ "${TOOL_DESTINATION}/example/tool.txt" script)
if(NOT script STREQUAL "version-2-updated")
    message(FATAL_ERROR "Tool-only update was not copied")
endif()
message(STATUS "Tool copy preserves state and updates scripts")
